<?php

namespace AppBundle\Repository;

/**
 * komentariRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class komentariRepository extends \Doctrine\ORM\EntityRepository
{
}
